name: phylobarcode 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7,<3.10 ## bugger! conda doesnt have a parasail 3.10 yet
  - primer3
  - pip
  - biopython
  - parasail-python 
  - scikit-learn 
  - numpy
  - pandas
  - python-xxhash
  - mafft>7.467
  - xz
  - blast 
  - vsearch
  - gffutils
  - dendropy
  - treeswift # only to calc cophenetic distances
  - cd-hit
  - rapidnj
  - fasttree
    #  - python>3.7
    #  - primer3>2.6.0
    #  - pip
    #  - biopython>1.70
    #  - parasail-python>1.2.3
    #  - scikit-learn 
    #  - numpy>1.22.2
    #  - pandas>1.4.1
    #  - blast>2.11.0
    #  - vsearch>2.20.1
    #  - python-xxhash>2.0.0 # equiv to xxhash 0.8.0
  - pip:
    - .  # this means run pip on this directory's setup.py 
    - pytools>2020.1
